my_aws_region = "Enter your region"
my_access_key = "Enter your access_key"
my_secret_key = "Enter your secret_key"
my_domain_name = "Enter your domain_name"
my_web_sub_domain_name = "Enter your web_sub_domain_name"
my_mail_sub_domain_name = "Enter your mail_sub_domain_name"
my_local_aws_private_key_path = "Enter your private_key_path"
my_key_name = "Enter your Key-pair_name"
